#!/usr/bin/env bash

go build -o bin/title title.go
gcc -Wall -O2 -o bin/script script.c
gcc -Wall -O2 -o bin/capitalise capitalise.c
gcc -Wall -O2 -o bin/capitalise-goto capitalise-goto.c
stack --local-bin-path bin install
